# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  commit_interval: 60
  purge_keep_days: 7
  include:
    domains:
      - sensor

sensor:
  - platform: systemmonitor
    scan_interval: 10
    resources:
      - type: disk_use_percent
      - type: memory_use_percent
      - type: swap_use_percent
      - type: processor_use
      - type: processor_temperature
      - type: load_1m

  - platform: command_line
    command: iwconfig wlan0 | grep Quality= | sed -r 's/^([^.]+).*$/\1/; s/^[^0-9]*([0-9]+).*$/\1/'
    name: Wifi Signal
    unit_of_measurement: '%'
    value_template: "{{ (value | int / 70*100) | round(0) }}"

  - platform: rest
    name: IMU
    resource: http://127.0.0.1:5000/IMU
    value_template: '{{ value_json }}'
    json_attributes:
      - AccX
      - AccY
      - Heading
    scan_interval: 1
  
  - platform: template
    sensors:
      accx:
        friendly_name: "Acceleration X"
        unit_of_measurement: "°"
        value_template: "{{state_attr('sensor.imu','AccX')}}"
      accy:
        friendly_name: "Acceleration Y"
        unit_of_measurement: "°"
        value_template: "{{state_attr('sensor.imu','AccY')}}"
      heading:
        friendly_name: "Heading"
        unit_of_measurement: "°"
        value_template: "{{state_attr('sensor.imu','Heading')}}"

      # https://no.wikipedia.org/wiki/Himmelretning#%C3%85tte_himmelretninger
      # https://community.home-assistant.io/t/sensor-wind-compass-up-for-grabs/52425
      heading_abbr:
        friendly_name: "Heading abbreviated"
        value_template: >-
          {% if 337.5 <= states('sensor.heading')|float <= 22.5 %}
             N
          {% elif 22.5 <= states('sensor.heading')|float <= 67.5 %}
             NE
          {% elif 67.5 <= states('sensor.heading')|float <= 112.5 %}
             E
          {% elif 112.5 <= states('sensor.heading')|float <= 157.5 %}
             SE
          {% elif 157.5 <= states('sensor.heading')|float <= 202.5 %}
             S
          {% elif 202.5 <= states('sensor.heading')|float <= 247.5 %}
             SW
          {% elif 247.5 <= states('sensor.heading')|float <= 292.5 %}
             W
          {% elif 292.5 <= states('sensor.heading')|float <= 337.5 %}
             NW
          {% endif %}

camera:
  - platform: mjpeg
    name: Rear Camera
    mjpeg_url: http://127.0.0.1:8080/mjpeg