# 2021.6.6 is the afaik latest before this issue https://github.com/alpinelinux/docker-alpine/issues/135
FROM homeassistant/home-assistant:2021.6.6

# For getting WiFi info
RUN apk update && apk add wireless-tools